version: 0.2
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 16
    commands:
      - npm i
  build:
    commands:
      - npm run build
artifacts:
  files:
    - "**/*"
  base-directory: dist/app
